name = "iptools"
main = "index.js"
compatibility_date = "2024-10-24"

# 环境变量配置（可选）
# [vars]
# GA_ID = "G-XXXXXXXXXX"  # Google Analytics ID

[env.production]
routes = [
  { pattern = "ip.plz.ac/*", zone_name = "plz.ac" }
]